services:
  dir-init:
    build: ./dir-init
    container_name: dir-init
    volumes:
      - ${DATA_DIR:-./data}:/data
      - ${LIBRARY_DIR:-./data}:/library
    environment:
      - DATA_DIR=/data
      - LIBRARY_DIR=/library
    restart: "no"

  db-init:
    build: ./db-init
    volumes:
      - ${DATA_DIR:-./data}/db:/app/db
    environment:
      - DB_PATH=/app/db/rss.sqlite
    depends_on:
      - dir-init
    restart: "no"
    healthcheck:
      test: ["CMD", "test", "-f", "/app/db/rss.sqlite"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ygg-gateway:
    build: ./ygg-gateway
    container_name: ygg-gateway
    environment:
      - YGG_API_BASE_URL=${YGG_API_BASE_URL:-https://yggapi.eu}
      - YGG_API_KEY=${YGG_API_KEY:-}
    depends_on:
      - dir-init
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  transmission:
    image: linuxserver/transmission:latest
    platform: linux/amd64
    container_name: torrent-client
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - USER=${TRANSMISSION_USER:-admin}
      - PASS=${TRANSMISSION_PASS:-admin}
    volumes:
      - ${DATA_DIR:-./data}/downloads:/downloads
      - ${DATA_DIR:-./data}/drop-torrents:/watch
      - transmission-config:/config
    ports:
      - "9091:9091"
    depends_on:
      - dir-init
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/transmission/web/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mover:
    build: ./mover
    container_name: mover
    volumes:
      - ${DATA_DIR:-./data}/downloads:/downloads
      - ${DATA_DIR:-./data}/toMerge:/toMerge
      - ${DATA_DIR:-./data}/converted:/converted
      - ${DATA_DIR:-./data}/toTag:/toTag
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - dir-init
      - api
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep -v grep | grep mover"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  tagger:
    build: ./tagger
    container_name: tagger
    volumes:
      - ${DATA_DIR:-./data}/toTag:/toTag
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TAGGER_SCAN_INTERVAL=${TAGGER_SCAN_INTERVAL:-60}
    depends_on:
      - dir-init
      - api
      - redis
    restart: unless-stopped
    networks:
      - default
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import redis; r=redis.Redis(host='redis', port=6379, db=0); r.ping()",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8081:8000"
    volumes:
      - ${DATA_DIR:-./data}/db:/app/db
      - ${DATA_DIR:-./data}/downloads:/app/downloads
      - ${DATA_DIR:-./data}/toMerge:/app/toMerge
      - ${DATA_DIR:-./data}/converted:/app/converted
      - ${DATA_DIR:-./data}/conversion-backups:/app/conversion-backups
      - ${LIBRARY_DIR:-${DATA_DIR:-./data}/library}:/app/library
      - ${DATA_DIR:-./data}/saved-torrents-files:/app/saved-torrents-files
      - ${DATA_DIR:-./data}/toTag:/app/toTag
      - ${DATA_DIR:-./data}/covers:/app/data/covers
      - ./converter:/app/converter
    environment:
      - LIBRARY_PATH=/app/library
      - COVERS_PATH=/app/data/covers
      - DB_PATH=/app/db/rss.sqlite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - TRANSMISSION_HOST=transmission
      - TRANSMISSION_PORT=9091
      - TRANSMISSION_USER=admin
      - TRANSMISSION_PASS=admin
      - YGG_GATEWAY_URL=http://ygg-gateway:8000
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    depends_on:
      - dir-init
      - transmission
      - db-init
      - redis
      - ygg-gateway
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  converter:
    build: ./converter
    container_name: converter
    volumes:
      - ${DATA_DIR:-./data}/toMerge:/toMerge
      - ${DATA_DIR:-./data}/converted:/converted
      - ${DATA_DIR:-./data}/conversion-backups:/backups
      - ${DATA_DIR:-./data}/db:/app/db
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DB_PATH=/app/db/rss.sqlite
      - API_URL=http://api:8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CONVERSION_MAX_RETRIES=3
      - CONVERSION_BACKUP_RETENTION=3
      - CONVERSION_TIMEOUT=7200
      - M4B_TOOL_BITRATE=128k
      - M4B_TOOL_CODEC=aac
    depends_on:
      - dir-init
      - api
      - db-init
      - redis
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import redis; r=redis.Redis(host='redis', port=6379, db=0); r.ping()",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ui:
    # Build UI with API URL (set VITE_API_URL environment variable for production)
    build:
      context: ./ui
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8081}
    ports:
      - "8080:3000"
    depends_on:
      - api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  transmission-config:
  redis-data:

x-data-directories: &data-directories
  - ${DATA_DIR:-./data}/drop-torrents
  - ${DATA_DIR:-./data}/downloads
  - ${DATA_DIR:-./data}/saved-torrents-files
  - ${DATA_DIR:-./data}/toMerge
  - ${DATA_DIR:-./data}/converted
  - ${DATA_DIR:-./data}/toTag
  - ${DATA_DIR:-./data}/conversion-backups
  - ${LIBRARY_DIR:-${DATA_DIR:-./data}}
  - ${DATA_DIR:-./data}/db
