// Generated types from FastAPI OpenAPI schema
// This file will be generated by openapi-typescript

export interface RSSItem {
  id: number;
  title: string;
  link: string;
  pub_date?: string;
  description?: string;
  author?: string;
  year?: string;
  format?: string;
  file_size?: string;
  seeders: number;
  leechers: number;
  torrent_url?: string;
  status: string;
  created_at: string;
  updated_at: string;
  download_status?: string;
  download_date?: string;
}

export interface Download {
  id: number;
  rss_item_id: number;
  status: string;
  path?: string;
  torrent_file?: string;
  created_at: string;
  updated_at: string;
}

export interface LogEntry {
  id: number;
  level: string;
  message: string;
  service?: string;
  created_at: string;
}

export interface TorrentInfo {
  id: number;
  name: string;
  status: string;
  progress: number;
  downloadDir: string;
}
export interface TaggingItem {
  id?: number;
  name: string;
  path: string;
  folder?: string;
  status: string;
  size?: number;
  auto_tagged?: boolean;
  message?: string;
  created_at?: string;
  updated_at?: string;
}

export interface Token {
  access_token: string;
  token_type: string;
}

export interface ApiResponse<T> {
  data: T;
  message?: string;
}
